"""Insert batch-2 feature strings into all twelve localization files.

Keeps each file's formatting intact by doing a single-line text insertion
after the "Common.Save" anchor instead of reserializing the JSON.
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1] / "src" / "DeskBox" / "Strings"

TRANSLATIONS: dict[str, dict[str, str]] = {
    "en-US": {
        "QuickCapture.ClipboardColor.Menu": "Record colors",
        "QuickCapture.ClipboardColor.FollowTheme": "Follow theme",
        "QuickCapture.ClipboardColor.Text": "Item text color…",
        "QuickCapture.ClipboardColor.Background": "Item background color…",
        "QuickCapture.ClipboardColor.Reset": "Reset to default",
        "QuickCapture.ClipboardColor.TextCustom": "Text: custom color",
        "QuickCapture.ClipboardColor.BackgroundCustom": "Background: custom color",
        "QuickCapture.ClipboardColor.RejectedTitle": "Color combination rejected",
        "QuickCapture.ClipboardColor.RejectedBody": "The contrast ratio is {0}, below the minimum of {1}. Text would be unreadable. Pick a lighter or darker color.",
        "Widget.TitleAppearance.Menu": "Title & icon",
        "Widget.TitleAppearance.AlignLeft": "Align left",
        "Widget.TitleAppearance.AlignCenter": "Align center",
        "Widget.TitleAppearance.AlignRight": "Align right",
        "Widget.TitleAppearance.AlignAll": "Apply this alignment to all widgets",
        "Widget.TitleAppearance.CustomIcon": "Choose custom icon…",
        "Widget.TitleAppearance.ResetIcon": "Restore default icon",
        "Widget.TitleAppearance.ResetAllIcons": "Restore default icons for all widgets",
        "Widget.Margin.Configure": "Margins…",
        "Widget.Margin.Uniform": "Uniform margin",
        "Widget.Margin.PerSide": "Per-side margins",
        "Widget.Margin.UniformValue": "Margin (px)",
        "Widget.Margin.Left": "Left (px)",
        "Widget.Margin.Top": "Top (px)",
        "Widget.Margin.Right": "Right (px)",
        "Widget.Margin.Bottom": "Bottom (px)",
        "Widget.Margin.Invalid": "Enter a whole number between {0} and {1}.",
        "Widget.Margin.ApplyToAll": "Apply to all visible widgets",
    },
    "zh-CN": {
        "QuickCapture.ClipboardColor.Menu": "记录配色",
        "QuickCapture.ClipboardColor.FollowTheme": "跟随主题",
        "QuickCapture.ClipboardColor.Text": "记录文字颜色…",
        "QuickCapture.ClipboardColor.Background": "记录背景颜色…",
        "QuickCapture.ClipboardColor.Reset": "恢复默认配色",
        "QuickCapture.ClipboardColor.TextCustom": "文字：自定义配色",
        "QuickCapture.ClipboardColor.BackgroundCustom": "背景：自定义配色",
        "QuickCapture.ClipboardColor.RejectedTitle": "配色组合不可用",
        "QuickCapture.ClipboardColor.RejectedBody": "对比度仅 {0}，低于最低要求 {1}，文字将无法阅读。请选择更亮或更深的颜色。",
        "Widget.TitleAppearance.Menu": "标题与图标",
        "Widget.TitleAppearance.AlignLeft": "左对齐",
        "Widget.TitleAppearance.AlignCenter": "居中对齐",
        "Widget.TitleAppearance.AlignRight": "右对齐",
        "Widget.TitleAppearance.AlignAll": "将该对齐应用到全部格子",
        "Widget.TitleAppearance.CustomIcon": "选择自定义图标…",
        "Widget.TitleAppearance.ResetIcon": "恢复默认图标",
        "Widget.TitleAppearance.ResetAllIcons": "恢复全部格子默认图标",
        "Widget.Margin.Configure": "边距设置…",
        "Widget.Margin.Uniform": "统一边距",
        "Widget.Margin.PerSide": "分边设置",
        "Widget.Margin.UniformValue": "边距（像素）",
        "Widget.Margin.Left": "左（像素）",
        "Widget.Margin.Top": "上（像素）",
        "Widget.Margin.Right": "右（像素）",
        "Widget.Margin.Bottom": "下（像素）",
        "Widget.Margin.Invalid": "请输入 {0} 到 {1} 之间的整数。",
        "Widget.Margin.ApplyToAll": "应用到全部可见格子",
    },
    "zh-TW": {
        "QuickCapture.ClipboardColor.Menu": "記錄配色",
        "QuickCapture.ClipboardColor.FollowTheme": "跟隨主題",
        "QuickCapture.ClipboardColor.Text": "記錄文字顏色…",
        "QuickCapture.ClipboardColor.Background": "記錄背景顏色…",
        "QuickCapture.ClipboardColor.Reset": "還原預設配色",
        "QuickCapture.ClipboardColor.TextCustom": "文字：自訂配色",
        "QuickCapture.ClipboardColor.BackgroundCustom": "背景：自訂配色",
        "QuickCapture.ClipboardColor.RejectedTitle": "配色組合無法使用",
        "QuickCapture.ClipboardColor.RejectedBody": "對比度僅 {0}，低於最低要求 {1}，文字將難以閱讀。請選擇更亮或更深的顏色。",
        "Widget.TitleAppearance.Menu": "標題與圖示",
        "Widget.TitleAppearance.AlignLeft": "靠左對齊",
        "Widget.TitleAppearance.AlignCenter": "置中對齊",
        "Widget.TitleAppearance.AlignRight": "靠右對齊",
        "Widget.TitleAppearance.AlignAll": "將此對齊套用至全部格子",
        "Widget.TitleAppearance.CustomIcon": "選擇自訂圖示…",
        "Widget.TitleAppearance.ResetIcon": "還原預設圖示",
        "Widget.TitleAppearance.ResetAllIcons": "還原全部格子預設圖示",
        "Widget.Margin.Configure": "邊界設定…",
        "Widget.Margin.Uniform": "統一邊界",
        "Widget.Margin.PerSide": "逐邊設定",
        "Widget.Margin.UniformValue": "邊界（像素）",
        "Widget.Margin.Left": "左（像素）",
        "Widget.Margin.Top": "上（像素）",
        "Widget.Margin.Right": "右（像素）",
        "Widget.Margin.Bottom": "下（像素）",
        "Widget.Margin.Invalid": "請輸入 {0} 到 {1} 之間的整數。",
        "Widget.Margin.ApplyToAll": "套用至全部可見格子",
    },
    "ja-JP": {
        "QuickCapture.ClipboardColor.Menu": "レコードの色",
        "QuickCapture.ClipboardColor.FollowTheme": "テーマに従う",
        "QuickCapture.ClipboardColor.Text": "項目の文字色…",
        "QuickCapture.ClipboardColor.Background": "項目の背景色…",
        "QuickCapture.ClipboardColor.Reset": "既定に戻す",
        "QuickCapture.ClipboardColor.TextCustom": "文字：カスタム色",
        "QuickCapture.ClipboardColor.BackgroundCustom": "背景：カスタム色",
        "QuickCapture.ClipboardColor.RejectedTitle": "色の組み合わせを却下",
        "QuickCapture.ClipboardColor.RejectedBody": "コントラスト比が {0} で、最低値 {1} を下回るため文字が判読できません。より明るい色または暗い色を選んでください。",
        "Widget.TitleAppearance.Menu": "タイトルとアイコン",
        "Widget.TitleAppearance.AlignLeft": "左揃え",
        "Widget.TitleAppearance.AlignCenter": "中央揃え",
        "Widget.TitleAppearance.AlignRight": "右揃え",
        "Widget.TitleAppearance.AlignAll": "この配置をすべてのウィジェットに適用",
        "Widget.TitleAppearance.CustomIcon": "カスタムアイコンを選択…",
        "Widget.TitleAppearance.ResetIcon": "既定のアイコンに戻す",
        "Widget.TitleAppearance.ResetAllIcons": "すべてのウィジェットのアイコンを既定に戻す",
        "Widget.Margin.Configure": "マージン設定…",
        "Widget.Margin.Uniform": "均一マージン",
        "Widget.Margin.PerSide": "辺ごとに設定",
        "Widget.Margin.UniformValue": "マージン（px）",
        "Widget.Margin.Left": "左（px）",
        "Widget.Margin.Top": "上（px）",
        "Widget.Margin.Right": "右（px）",
        "Widget.Margin.Bottom": "下（px）",
        "Widget.Margin.Invalid": "{0} から {1} の整数を入力してください。",
        "Widget.Margin.ApplyToAll": "表示中のすべてのウィジェットに適用",
    },
    "de-DE": {
        "QuickCapture.ClipboardColor.Menu": "Eintragsfarben",
        "QuickCapture.ClipboardColor.FollowTheme": "Design folgen",
        "QuickCapture.ClipboardColor.Text": "Textfarbe der Einträge…",
        "QuickCapture.ClipboardColor.Background": "Hintergrundfarbe der Einträge…",
        "QuickCapture.ClipboardColor.Reset": "Auf Standard zurücksetzen",
        "QuickCapture.ClipboardColor.TextCustom": "Text: eigene Farbe",
        "QuickCapture.ClipboardColor.BackgroundCustom": "Hintergrund: eigene Farbe",
        "QuickCapture.ClipboardColor.RejectedTitle": "Farbkombination abgelehnt",
        "QuickCapture.ClipboardColor.RejectedBody": "Das Kontrastverhältnis beträgt {0} und liegt unter dem Minimum von {1}. Text wäre unlesbar. Wählen Sie eine hellere oder dunklere Farbe.",
        "Widget.TitleAppearance.Menu": "Titel & Symbol",
        "Widget.TitleAppearance.AlignLeft": "Linksbündig",
        "Widget.TitleAppearance.AlignCenter": "Zentriert",
        "Widget.TitleAppearance.AlignRight": "Rechtsbündig",
        "Widget.TitleAppearance.AlignAll": "Ausrichtung auf alle Widgets anwenden",
        "Widget.TitleAppearance.CustomIcon": "Eigenes Symbol wählen…",
        "Widget.TitleAppearance.ResetIcon": "Standardsymbol wiederherstellen",
        "Widget.TitleAppearance.ResetAllIcons": "Standardsymbole aller Widgets wiederherstellen",
        "Widget.Margin.Configure": "Ränder…",
        "Widget.Margin.Uniform": "Einheitlicher Rand",
        "Widget.Margin.PerSide": "Rand je Seite",
        "Widget.Margin.UniformValue": "Rand (px)",
        "Widget.Margin.Left": "Links (px)",
        "Widget.Margin.Top": "Oben (px)",
        "Widget.Margin.Right": "Rechts (px)",
        "Widget.Margin.Bottom": "Unten (px)",
        "Widget.Margin.Invalid": "Ganze Zahl zwischen {0} und {1} eingeben.",
        "Widget.Margin.ApplyToAll": "Auf alle sichtbaren Widgets anwenden",
    },
    "fr-FR": {
        "QuickCapture.ClipboardColor.Menu": "Couleurs des entrées",
        "QuickCapture.ClipboardColor.FollowTheme": "Suivre le thème",
        "QuickCapture.ClipboardColor.Text": "Couleur du texte des entrées…",
        "QuickCapture.ClipboardColor.Background": "Couleur de fond des entrées…",
        "QuickCapture.ClipboardColor.Reset": "Rétablir la valeur par défaut",
        "QuickCapture.ClipboardColor.TextCustom": "Texte : couleur personnalisée",
        "QuickCapture.ClipboardColor.BackgroundCustom": "Arrière-plan : couleur personnalisée",
        "QuickCapture.ClipboardColor.RejectedTitle": "Combinaison de couleurs refusée",
        "QuickCapture.ClipboardColor.RejectedBody": "Le rapport de contraste est de {0}, inférieur au minimum de {1}. Le texte serait illisible. Choisissez une couleur plus claire ou plus foncée.",
        "Widget.TitleAppearance.Menu": "Titre & icône",
        "Widget.TitleAppearance.AlignLeft": "Aligner à gauche",
        "Widget.TitleAppearance.AlignCenter": "Centrer",
        "Widget.TitleAppearance.AlignRight": "Aligner à droite",
        "Widget.TitleAppearance.AlignAll": "Appliquer cet alignement à tous les widgets",
        "Widget.TitleAppearance.CustomIcon": "Choisir une icône personnalisée…",
        "Widget.TitleAppearance.ResetIcon": "Restaurer l'icône par défaut",
        "Widget.TitleAppearance.ResetAllIcons": "Restaurer les icônes par défaut de tous les widgets",
        "Widget.Margin.Configure": "Marges…",
        "Widget.Margin.Uniform": "Marge uniforme",
        "Widget.Margin.PerSide": "Marge par côté",
        "Widget.Margin.UniformValue": "Marge (px)",
        "Widget.Margin.Left": "Gauche (px)",
        "Widget.Margin.Top": "Haut (px)",
        "Widget.Margin.Right": "Droite (px)",
        "Widget.Margin.Bottom": "Bas (px)",
        "Widget.Margin.Invalid": "Saisissez un nombre entier entre {0} et {1}.",
        "Widget.Margin.ApplyToAll": "Appliquer à tous les widgets visibles",
    },
    "es-ES": {
        "QuickCapture.ClipboardColor.Menu": "Colores de registros",
        "QuickCapture.ClipboardColor.FollowTheme": "Seguir el tema",
        "QuickCapture.ClipboardColor.Text": "Color del texto de los registros…",
        "QuickCapture.ClipboardColor.Background": "Color de fondo de los registros…",
        "QuickCapture.ClipboardColor.Reset": "Restaurar valores predeterminados",
        "QuickCapture.ClipboardColor.TextCustom": "Texto: color personalizado",
        "QuickCapture.ClipboardColor.BackgroundCustom": "Fondo: color personalizado",
        "QuickCapture.ClipboardColor.RejectedTitle": "Combinación de colores rechazada",
        "QuickCapture.ClipboardColor.RejectedBody": "La relación de contraste es {0}, inferior al mínimo de {1}. El texto sería ilegible. Elija un color más claro u oscuro.",
        "Widget.TitleAppearance.Menu": "Título e icono",
        "Widget.TitleAppearance.AlignLeft": "Alinear a la izquierda",
        "Widget.TitleAppearance.AlignCenter": "Centrar",
        "Widget.TitleAppearance.AlignRight": "Alinear a la derecha",
        "Widget.TitleAppearance.AlignAll": "Aplicar esta alineación a todos los widgets",
        "Widget.TitleAppearance.CustomIcon": "Elegir icono personalizado…",
        "Widget.TitleAppearance.ResetIcon": "Restaurar icono predeterminado",
        "Widget.TitleAppearance.ResetAllIcons": "Restaurar iconos predeterminados de todos los widgets",
        "Widget.Margin.Configure": "Márgenes…",
        "Widget.Margin.Uniform": "Margen uniforme",
        "Widget.Margin.PerSide": "Márgenes por lado",
        "Widget.Margin.UniformValue": "Margen (px)",
        "Widget.Margin.Left": "Izquierda (px)",
        "Widget.Margin.Top": "Arriba (px)",
        "Widget.Margin.Right": "Derecha (px)",
        "Widget.Margin.Bottom": "Abajo (px)",
        "Widget.Margin.Invalid": "Escriba un número entero entre {0} y {1}.",
        "Widget.Margin.ApplyToAll": "Aplicar a todos los widgets visibles",
    },
    "pt-BR": {
        "QuickCapture.ClipboardColor.Menu": "Cores dos registros",
        "QuickCapture.ClipboardColor.FollowTheme": "Seguir o tema",
        "QuickCapture.ClipboardColor.Text": "Cor do texto dos registros…",
        "QuickCapture.ClipboardColor.Background": "Cor de fundo dos registros…",
        "QuickCapture.ClipboardColor.Reset": "Restaurar padrão",
        "QuickCapture.ClipboardColor.TextCustom": "Texto: cor personalizada",
        "QuickCapture.ClipboardColor.BackgroundCustom": "Fundo: cor personalizada",
        "QuickCapture.ClipboardColor.RejectedTitle": "Combinação de cores rejeitada",
        "QuickCapture.ClipboardColor.RejectedBody": "A taxa de contraste é {0}, abaixo do mínimo de {1}. O texto ficaria ilegível. Escolha uma cor mais clara ou mais escura.",
        "Widget.TitleAppearance.Menu": "Título e ícone",
        "Widget.TitleAppearance.AlignLeft": "Alinhar à esquerda",
        "Widget.TitleAppearance.AlignCenter": "Centralizar",
        "Widget.TitleAppearance.AlignRight": "Alinhar à direita",
        "Widget.TitleAppearance.AlignAll": "Aplicar este alinhamento a todos os widgets",
        "Widget.TitleAppearance.CustomIcon": "Escolher ícone personalizado…",
        "Widget.TitleAppearance.ResetIcon": "Restaurar ícone padrão",
        "Widget.TitleAppearance.ResetAllIcons": "Restaurar ícones padrão de todos os widgets",
        "Widget.Margin.Configure": "Margens…",
        "Widget.Margin.Uniform": "Margem uniforme",
        "Widget.Margin.PerSide": "Margens por lado",
        "Widget.Margin.UniformValue": "Margem (px)",
        "Widget.Margin.Left": "Esquerda (px)",
        "Widget.Margin.Top": "Superior (px)",
        "Widget.Margin.Right": "Direita (px)",
        "Widget.Margin.Bottom": "Inferior (px)",
        "Widget.Margin.Invalid": "Digite um número inteiro entre {0} e {1}.",
        "Widget.Margin.ApplyToAll": "Aplicar a todos os widgets visíveis",
    },
    "ru-RU": {
        "QuickCapture.ClipboardColor.Menu": "Цвета записей",
        "QuickCapture.ClipboardColor.FollowTheme": "Как в теме",
        "QuickCapture.ClipboardColor.Text": "Цвет текста записей…",
        "QuickCapture.ClipboardColor.Background": "Цвет фона записей…",
        "QuickCapture.ClipboardColor.Reset": "Вернуть по умолчанию",
        "QuickCapture.ClipboardColor.TextCustom": "Текст: свой цвет",
        "QuickCapture.ClipboardColor.BackgroundCustom": "Фон: свой цвет",
        "QuickCapture.ClipboardColor.RejectedTitle": "Сочетание цветов отклонено",
        "QuickCapture.ClipboardColor.RejectedBody": "Коэффициент контрастности {0} ниже минимума {1}. Текст будет нечитаемым. Выберите более светлый или тёмный цвет.",
        "Widget.TitleAppearance.Menu": "Заголовок и значок",
        "Widget.TitleAppearance.AlignLeft": "По левому краю",
        "Widget.TitleAppearance.AlignCenter": "По центру",
        "Widget.TitleAppearance.AlignRight": "По правому краю",
        "Widget.TitleAppearance.AlignAll": "Применить это выравнивание ко всем виджетам",
        "Widget.TitleAppearance.CustomIcon": "Выбрать свой значок…",
        "Widget.TitleAppearance.ResetIcon": "Вернуть значок по умолчанию",
        "Widget.TitleAppearance.ResetAllIcons": "Вернуть значки по умолчанию для всех виджетов",
        "Widget.Margin.Configure": "Отступы…",
        "Widget.Margin.Uniform": "Единый отступ",
        "Widget.Margin.PerSide": "Отступы по сторонам",
        "Widget.Margin.UniformValue": "Отступ (пикс.)",
        "Widget.Margin.Left": "Слева (пикс.)",
        "Widget.Margin.Top": "Сверху (пикс.)",
        "Widget.Margin.Right": "Справа (пикс.)",
        "Widget.Margin.Bottom": "Снизу (пикс.)",
        "Widget.Margin.Invalid": "Введите целое число от {0} до {1}.",
        "Widget.Margin.ApplyToAll": "Применить ко всем видимым виджетам",
    },
    "ar-SA": {
        "QuickCapture.ClipboardColor.Menu": "ألوان السجلات",
        "QuickCapture.ClipboardColor.FollowTheme": "اتباع السمة",
        "QuickCapture.ClipboardColor.Text": "لون نص السجلات…",
        "QuickCapture.ClipboardColor.Background": "لون خلفية السجلات…",
        "QuickCapture.ClipboardColor.Reset": "استعادة الافتراضي",
        "QuickCapture.ClipboardColor.TextCustom": "النص: لون مخصص",
        "QuickCapture.ClipboardColor.BackgroundCustom": "الخلفية: لون مخصص",
        "QuickCapture.ClipboardColor.RejectedTitle": "تم رفض مجموعة الألوان",
        "QuickCapture.ClipboardColor.RejectedBody": "نسبة التباين {0}، وهي أقل من الحد الأدنى {1}. سيكون النص غير مقروء. اختر لوناً أفتح أو أغمق.",
        "Widget.TitleAppearance.Menu": "العنوان والأيقونة",
        "Widget.TitleAppearance.AlignLeft": "محاذاة لليسار",
        "Widget.TitleAppearance.AlignCenter": "توسيط",
        "Widget.TitleAppearance.AlignRight": "محاذاة لليمين",
        "Widget.TitleAppearance.AlignAll": "تطبيق هذه المحاذاة على جميع الأدوات",
        "Widget.TitleAppearance.CustomIcon": "اختيار أيقونة مخصصة…",
        "Widget.TitleAppearance.ResetIcon": "استعادة الأيقونة الافتراضية",
        "Widget.TitleAppearance.ResetAllIcons": "استعادة الأيقونات الافتراضية لجميع الأدوات",
        "Widget.Margin.Configure": "الهوامش…",
        "Widget.Margin.Uniform": "هامش موحد",
        "Widget.Margin.PerSide": "هوامش لكل جانب",
        "Widget.Margin.UniformValue": "الهامش (بكسل)",
        "Widget.Margin.Left": "يسار (بكسل)",
        "Widget.Margin.Top": "أعلى (بكسل)",
        "Widget.Margin.Right": "يمين (بكسل)",
        "Widget.Margin.Bottom": "أسفل (بكسل)",
        "Widget.Margin.Invalid": "أدخل رقماً صحيحاً بين {0} و{1}.",
        "Widget.Margin.ApplyToAll": "التطبيق على جميع الأدوات المرئية",
    },
    "hi-IN": {
        "QuickCapture.ClipboardColor.Menu": "रिकॉर्ड रंग",
        "QuickCapture.ClipboardColor.FollowTheme": "थीम का पालन करें",
        "QuickCapture.ClipboardColor.Text": "रिकॉर्ड टेक्स्ट रंग…",
        "QuickCapture.ClipboardColor.Background": "रिकॉर्ड पृष्ठभूमि रंग…",
        "QuickCapture.ClipboardColor.Reset": "डिफ़ॉल्ट पर रीसेट करें",
        "QuickCapture.ClipboardColor.TextCustom": "टेक्स्ट: कस्टम रंग",
        "QuickCapture.ClipboardColor.BackgroundCustom": "पृष्ठभूमि: कस्टम रंग",
        "QuickCapture.ClipboardColor.RejectedTitle": "रंग संयोजन अस्वीकृत",
        "QuickCapture.ClipboardColor.RejectedBody": "कंट्रास्ट अनुपात {0} है, जो न्यूनतम {1} से कम है। टेक्स्ट अपठनीय होगा। कोई हल्का या गहरा रंग चुनें।",
        "Widget.TitleAppearance.Menu": "शीर्षक और आइकन",
        "Widget.TitleAppearance.AlignLeft": "बाएँ संरेखित करें",
        "Widget.TitleAppearance.AlignCenter": "केंद्र में रखें",
        "Widget.TitleAppearance.AlignRight": "दाएँ संरेखित करें",
        "Widget.TitleAppearance.AlignAll": "यह संरेखण सभी विजेट पर लागू करें",
        "Widget.TitleAppearance.CustomIcon": "कस्टम आइकन चुनें…",
        "Widget.TitleAppearance.ResetIcon": "डिफ़ॉल्ट आइकन पुनर्स्थापित करें",
        "Widget.TitleAppearance.ResetAllIcons": "सभी विजेट के डिफ़ॉल्ट आइकन पुनर्स्थापित करें",
        "Widget.Margin.Configure": "मार्जिन…",
        "Widget.Margin.Uniform": "समान मार्जिन",
        "Widget.Margin.PerSide": "प्रति-भुजा मार्जिन",
        "Widget.Margin.UniformValue": "मार्जिन (px)",
        "Widget.Margin.Left": "बाएँ (px)",
        "Widget.Margin.Top": "ऊपर (px)",
        "Widget.Margin.Right": "दाएँ (px)",
        "Widget.Margin.Bottom": "नीचे (px)",
        "Widget.Margin.Invalid": "{0} से {1} के बीच पूर्णांक दर्ज करें।",
        "Widget.Margin.ApplyToAll": "सभी दृश्यमान विजेट पर लागू करें",
    },
    "bn-BD": {
        "QuickCapture.ClipboardColor.Menu": "রেকর্ডের রং",
        "QuickCapture.ClipboardColor.FollowTheme": "থিম অনুসরণ করুন",
        "QuickCapture.ClipboardColor.Text": "রেকর্ডের লেখার রং…",
        "QuickCapture.ClipboardColor.Background": "রেকর্ডের পটভূমির রং…",
        "QuickCapture.ClipboardColor.Reset": "ডিফল্টে ফিরিয়ে আনুন",
        "QuickCapture.ClipboardColor.TextCustom": "লেখা: কাস্টম রং",
        "QuickCapture.ClipboardColor.BackgroundCustom": "পটভূমি: কাস্টম রং",
        "QuickCapture.ClipboardColor.RejectedTitle": "রঙের সমন্বয় বাতিল",
        "QuickCapture.ClipboardColor.RejectedBody": "কনট্রাস্ট অনুপাত {0}, যা সর্বনিম্ন {1} এর নিচে। লেখা অপঠনযোগ্য হবে। হালকা বা গাঢ় রং বেছে নিন।",
        "Widget.TitleAppearance.Menu": "শিরোনাম ও আইকন",
        "Widget.TitleAppearance.AlignLeft": "বামে সারিবদ্ধ",
        "Widget.TitleAppearance.AlignCenter": "মাঝখানে সারিবদ্ধ",
        "Widget.TitleAppearance.AlignRight": "ডানে সারিবদ্ধ",
        "Widget.TitleAppearance.AlignAll": "এই সারিবদ্ধতা সব উইজেটে প্রয়োগ করুন",
        "Widget.TitleAppearance.CustomIcon": "কাস্টম আইকন নির্বাচন…",
        "Widget.TitleAppearance.ResetIcon": "ডিফল্ট আইকন ফিরিয়ে আনুন",
        "Widget.TitleAppearance.ResetAllIcons": "সব উইজেটের ডিফল্ট আইকন ফিরিয়ে আনুন",
        "Widget.Margin.Configure": "মার্জিন…",
        "Widget.Margin.Uniform": "অভিন্ন মার্জিন",
        "Widget.Margin.PerSide": "প্রতি পাশে মার্জিন",
        "Widget.Margin.UniformValue": "মার্জিন (px)",
        "Widget.Margin.Left": "বাম (px)",
        "Widget.Margin.Top": "উপরে (px)",
        "Widget.Margin.Right": "ডান (px)",
        "Widget.Margin.Bottom": "নিচে (px)",
        "Widget.Margin.Invalid": "{0} থেকে {1} এর মধ্যে একটি পূর্ণসংখ্যা লিখুন।",
        "Widget.Margin.ApplyToAll": "সব দৃশ্যমান উইজেটে প্রয়োগ করুন",
    },
}


def main() -> None:
    anchor = '"Common.Save"'
    inserted_total = 0
    for locale, strings in TRANSLATIONS.items():
        path = ROOT / f"{locale}.json"
        lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
        anchor_index = next(
            (i for i, line in enumerate(lines) if anchor in line),
            None,
        )
        if anchor_index is None:
            raise SystemExit(f"anchor not found in {path}")

        existing = set(json.loads(path.read_text(encoding="utf-8")).keys())
        new_lines = []
        for key, value in strings.items():
            if key in existing:
                continue
            escaped = (
                value.replace("\\", "\\\\").replace('"', '\\"'))
            new_lines.append(f'    "{key}": "{escaped}",\n')
        if not new_lines:
            print(f"{locale}: nothing to insert")
            continue

        lines[anchor_index + 1:anchor_index + 1] = new_lines
        path.write_text("".join(lines), encoding="utf-8", newline="\n")
        inserted_total += len(new_lines)
        print(f"{locale}: inserted {len(new_lines)} keys")

    # Every file must keep identical key coverage; verify.
    reference = set(json.loads((ROOT / "en-US.json").read_text(encoding="utf-8")).keys())
    for path in sorted(ROOT.glob("*.json")):
        keys = set(json.loads(path.read_text(encoding="utf-8")).keys())
        missing = reference - keys
        if missing:
            raise SystemExit(f"{path.name} missing keys: {sorted(missing)}")
    print(f"done; inserted {inserted_total} total; key coverage verified")


if __name__ == "__main__":
    main()
